### ISSUE TITLE
Começando os trabalhos

### ISSUE THREAD

**Issue by mvfsilva** [bahiacoders/bc-webpage#1]
Estava pensando em criarmos o site usando polymer com jekyll, php ou python, o que acham?

**Comment by Jadergomes** [comment]
O uso do Jekyll com elementos do Polymer, pra mim ta tranquilo. Só não peguei aonde entraria o python ou php.

**Comment by jonataa** [comment]
Concordo com o Jekyll, mas se quiser utilizar tecnologias JS, podemos dar uma olhada no [Metalsmith](https://docpad.org/) ou no [DocPad](https://docpad.org/). No caso do Polymer, recomendo utilizar o [Polymer Starter Kit](https://developers.google.com/web/tools/polymer-starter-kit/) como base.

Se quiserem utilizar algo mais simples, como um "Bootstrap com Material Design", lançaram recentemente o [Material Design Lite](http://www.getmdl.io/). Inclusive, aqui tem alguns [templates](http://www.getmdl.io/templates/index.html), podemos utiliza-los como base do site.

hehe opções é o que não falta! :)

**Comment by mvfsilva** [comment]
Pronto, faremos em jekyll, hoje mesmo já mando a estrutura pra cá.

Less, Sass ou Stylus?

**Comment by Jadergomes** [comment]
Stylus

**Comment by mvfsilva** [comment]
Então posso subir a estrutura?

**Comment by Jadergomes** [comment]
Ontem, huahua. Mas qual static Generator será usado velho?

**Comment by mvfsilva** [comment]
Jekyll

2015-07-10 14:13 GMT-03:00 Jader Gomes <notifications@github.com>:

> Ontem, huahua. Mas qual static Generator será usado velho?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bahiacoders/bc-webpage/issues/1#issuecomment-120462975>
> .
>



-- 
Atenciosamente,

*Marcus Silva*

Cursando nível superior em Analise e Desenvolvimento de Sistemas pelo SENAI
Unidade CIMATEC.

Formado em Desenvolvimento de Software pelo SENAI unidade CETIND.

(71)8287-4948

mvf.silva@hotmail.com | mvfsilva23@gmail.com

**Comment by Jadergomes** [comment]
Massa. Jekyll é uma ótima por já conhecermos, adianta o lado. Mas se tiver uma em Js aí legal tbm eu arriscaria mais uma, duas horas de estudo :)

**Comment by mvfsilva** [comment]
Desculpa galera, mas estou sem tempo para me dedicar a estudar outro gerador no momento, devido a projetos particulares;

**Comment by Jadergomes** [comment]
Eu aprovo o Jekyll pra gente adiantar o lado, esse projeto do BC já tem mais de um ano no papel cara. E aí @jonataa  @isaquediasm  ?

**Comment by jonataa** [comment]
Vamos de Jekyll mesmo. Já definiram o conteúdo desse site?

Em sex, 10 de jul de 2015 às 14:55, Jader Gomes <notifications@github.com>
escreveu:
